### ISSUE TITLE
Weird interaction with one probe, immersive railroading and pehkui

### ISSUE THREAD

**Issue by CanInBad** [Changeling-Gaming/Dragonspire-Reborn-Avali#6]
Description: error spams the console every time one probe is enabled and previewing immersive railroading's locomotive

small part of the error
`[15:53:23] [Render thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 949ef262-e762-4edc-9a58-9e2ce45fa4cc
[15:53:23] [Render thread/ERROR] [mc.th.TheOneProbe/]: Error rendering entity!
net.minecraft.crash.ReportedException: Rendering entity in world
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:279) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.EntityRenderDispatcherMixin,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.EntityRenderDispatcherMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at mcjty.theoneprobe.rendering.RenderHelper.renderEntity(RenderHelper.java:67) ~[theoneprobe:1.16-3.1.4] {re:classloading}
	at mcjty.theoneprobe.apiimpl.client.ElementEntityRender.renderEntity(ElementEntityRender.java:185) ~[theoneprobe:1.16-3.1.4] {re:classloading}
	at mcjty.theoneprobe.apiimpl.client.ElementEntityRender.render(ElementEntityRender.java:73) ~[theoneprobe:1.16-3.1.4] {re:classloading}
	at mcjty.theoneprobe.apiimpl.elements.ElementEntity.render(ElementEntity.java:70) ~[theoneprobe:1.16-3.1.4] {re:classloading}
	at mcjty.theoneprobe.apiimpl.elements.ElementHorizontal.render(ElementHorizontal.java:54) ~[theoneprobe:1.16-3.1.4] {re:classloading}
	at mcjty.theoneprobe.apiimpl.elements.ElementVertical.render(ElementVertical.java:54) ~[theoneprobe:1.16-3.1.4] {re:classloading}
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderElements(OverlayRenderer.java:433) ~[theoneprobe:1.16-3.1.4] {re:classloading}
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUDEntity(OverlayRenderer.java:200) ~[theoneprobe:1.16-3.1.4] {re:classloading}
	at mcjty.theoneprobe.rendering.OverlayRenderer.renderHUD(OverlayRenderer.java:86) ~[theoneprobe:1.16-3.1.4] {re:classloading}
	at mcjty.theoneprobe.proxy.ClientProxy.renderGameOverlayEvent(ClientProxy.java:110) ~[theoneprobe:1.16-3.1.4] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_809_ClientProxy_renderGameOverlayEvent_Pre.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.client.gui.ForgeIngameGui.renderHUDText(ForgeIngameGui.java:634) ~[forge:?] {re:mixin,re:classloading,xf:fml:xaerominimap:xaero_forgeingamegui_render,pl:mixin:APP:mixins.betterf3.json:ForgeIngameGuiMixin,pl:mixin:A}
	at net.minecraftforge.client.gui.ForgeIngameGui.func_238445_a_(ForgeIngameGui.java:187) ~[forge:?] {re:mixin,re:classloading,xf:fml:xaerominimap:xaero_forgeingamegui_render,pl:mixin:APP:mixins.betterf3.json:ForgeIngameGuiMixin,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:472) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.2-launcher.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:52) [ForgeWrapper-1.5.1.jar:1.5.1] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?] {re:classloading}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?] {re:classloading}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {re:classloading}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {re:classloading}
Caused by: java.lang.RuntimeException: Definition null has been removed!  This stock will not function!
	at cam72cam.immersiverailroading.entity.EntityRollingStock.getDefinition(EntityRollingStock.java:81) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.immersiverailroading.entity.LocomotiveSteam.getDefinition(LocomotiveSteam.java:58) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.immersiverailroading.entity.LocomotiveSteam.getDefinition(LocomotiveSteam.java:27) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.immersiverailroading.ImmersiveRailroading.lambda$clientEvent$0(ImmersiveRailroading.java:138) ~[immersiverailroading:1.16.5-forge-1.9.1] {re:classloading}
	at cam72cam.mod.render.EntityRenderer.render(EntityRenderer.java:163) ~[universalmodcore:1.1.3] {re:classloading}
	at cam72cam.mod.render.EntityRenderer.func_225623_a_(EntityRenderer.java:40) ~[universalmodcore:1.1.3] {re:classloading}
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:notenoughcrashes.mixins.json:client.EntityRenderDispatcherMixin,pl:mixin:APP:pehkui.mixins.json:client.compat115plus.EntityRenderDispatcherMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	... 43 more`

full log
[log.txt](https://github.com/Changeling-Gaming/Dragonspire-Reborn-Avali/files/7109525/log.txt)

**Comment by Nyinxie** [comment]
That's normal, you'll need to ignore it, Immersive railroading renders the full model in the item preview, and will probably make things complain that try to render it beyond the player's hand.
