### ISSUE TITLE
CPM phrase error/Failed to load model

### ISSUE THREAD

**Issue by CanInBad** [Changeling-Gaming/Dragonspire-Reborn-Avali#9]
This may related to issue #7 but idk

This is log from other person (ign: EggAvali Mc UUID: 9cd7701f-78d04b4a-b08a-0bd6a4e1e03d ) that I help troubleshoot with
and **I don't personally use CPM myself and did not request for the file of the CPM project** though I will ask they to provide with the project or you can ask them yourselfs

on line 3159 of this [paste.ee](https://paste.ee/p/8Sd87)
https://paste.ee/p/8Sd87#s=0&l=3159 (link directed to L 3159)
lies this

`[03:11:42] [pool-5-thread-3/ERROR] [CPM/]: Failed to load model
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Illegal base64 character a
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217) ~[guava-21.0.jar:?] {}
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154) ~[guava-21.0.jar:?] {}
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060) ~[guava-21.0.jar:?] {}
	at com.tom.cpm.shared.definition.ModelDefinitionLoader.load(ModelDefinitionLoader.java:175) ~[cpm:0.1.1b] {re:classloading}
	at com.tom.cpm.shared.parts.ModelPartLink.resolve(ModelPartLink.java:28) ~[cpm:0.1.1b] {re:classloading}
	at com.tom.cpm.shared.definition.ModelDefinition.resolveAll(ModelDefinition.java:143) ~[cpm:0.1.1b] {re:mixin,re:classloading}
	at com.tom.cpm.shared.definition.ModelDefinition.lambda$startResolve$0(ModelDefinition.java:98) ~[cpm:0.1.1b] {re:mixin,re:classloading}
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_281] {}
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_281] {}
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_281] {}
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_281] {}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281] {}
Caused by: java.lang.IllegalArgumentException: Illegal base64 character a
	at java.util.Base64$Decoder.decode0(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.Base64$Decoder.decode(Unknown Source) ~[?:1.8.0_281] {}
	at java.util.Base64$Decoder.decode(Unknown Source) ~[?:1.8.0_281] {}
	at com.tom.cpm.shared.loaders.HttpResourceLoader.loadResource(HttpResourceLoader.java:45) ~[cpm:0.1.1b] {re:classloading}
	at com.tom.cpm.shared.definition.ModelDefinitionLoader.load0(ModelDefinitionLoader.java:187) ~[cpm:0.1.1b] {re:classloading}
	at com.tom.cpm.shared.definition.ModelDefinitionLoader.lambda$load$2(ModelDefinitionLoader.java:175) ~[cpm:0.1.1b] {re:classloading}
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065) ~[guava-21.0.jar:?] {}
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) ~[guava-21.0.jar:?] {}
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) ~[guava-21.0.jar:?] {}
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) ~[guava-21.0.jar:?] {}
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) ~[guava-21.0.jar:?] {}
	... 11 more`

Another note to this is that they also get force disconnected after this if you see the full log though there is none indicated that happen.

**Comment by CanInBad** [comment]
closed due to being unrelated, will reopen with proper description of the issue
